#Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/bmj_db
# spring.datasource.username=root
# spring.datasource.password=rADHASOAMI@0
spring.datasource.username=bmj
spring.datasource.password=rADHASOAMI$8
spring.mvc.pathmatch.max-cache-size=2048

# Shopify Configuration
shopify.store-url=https://bookmyjuice.myshopify.com
shopify.storefront-access-token=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
shopify.api-version=2025-04 

#redis
# spring.cache.type=redis
# spring.data.redis.host=localhost
# spring.data.redis.port=6379
# redis.address=redis://localhost:6379

#JPA
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
#Server
server.port=8080
server.address =localhost
#Jackson
spring.jackson.serialization.indent-output=true

# chargebee.site=lush-j-test
# chargebee.chargebeeApiKey=your_chargebee_api_key
# chargebee.ratelimiter.limit-refresh-period=60
# chargebee.ratelimiter.limit-for-period=90
# chargebee.ratelimiter.timeout-duration=5


# App Properties
bezkoder.app.jwtSecret= ==========================BMJ============================
bezkoder.app.jwtExpirationMs=86400000

#chargebe
# Chargebee.site ="bmj-test"
# chargebee.api-key = test_I81nGTgs70tKBOk1rot41lFlg6SsGpQD
# chargebee.webhook-key= ${CHARGEBEE_WEBHOOK_KEY}
# chargebee.connect-timeout= 30000  # 30 seconds
# chargebee.socket-timeout= 60000   # 60 seconds
  
